name: villagerio
description: An app for seeking werewolf game party
publish_to: none
version: 0.1.5+230723
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  logger: ^1.4.0
  firebase_core: ^2.14.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  url_strategy: ^0.2.0
  awesome_select: ^6.0.0
  package_info_plus: ^4.0.2
  flutter_form_builder: ^9.0.0
  flutter_material_color_picker: ^1.2.0
  emoji_picker_flutter: ^1.6.1
  flutter_native_splash: ^2.3.1
  qr_flutter: ^4.1.0
  clipboard: ^0.1.3
  marquee: ^2.2.3
  carousel_slider: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/wallpaper/main.jpg
